// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveInfoView is a UI-facing snapshot of the archive state.
 */
export interface ArchiveInfoView {
    "path": string;
    "fileCount": number;
    "groupCount": number;
    "bodySize": number;
    "modifiedCount": number;
    "usesGuard": boolean;
    "paged110": boolean;
    "format": string;
    "contentRules": ContentRules;
    "writeCapabilities": WriteCapabilities;
}

/**
 * ContentRules describes client content conventions independently of the
 * physical container. Future containers can reuse or combine these rules.
 */
export interface ContentRules {
    "utf16Only": boolean;
    "requiresIndexHash": boolean;
    "supportsStringReferences": boolean;
}

/**
 * StringTableIndexStats counts actual lazy builds, not cached lookups.
 * Durations and payload counts are cumulative for this archive instance.
 */
export interface StringTableIndexStats {
    "revision": number;
    "state": string;
    "activeBuilds": number;
    "mappingBuilds": number;
    "mappingCount": number;
    "tableBuilds": number;
    "failedTables": number;
    "entries": number;
    "bytes": number;
    "mappingDurationMs": number;
    "tableDurationMs": number;
    "buildDurationMs": number;
}

/**
 * WriteCapabilities is derived from both the format and recovered archive
 * state. Structural edits include appending or remapping string-pool entries.
 */
export interface WriteCapabilities {
    "canSave": boolean;
    "canChangeStructure": boolean;
    "reason": string;
}
