// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveInfoView is a UI-facing snapshot of the archive state.
 */
export interface ArchiveInfoView {
    "path": string;
    "fileCount": number;
    "groupCount": number;
    "bodySize": number;
    "modifiedCount": number;
    "usesGuard": boolean;
}
