// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Descriptor {
    "id": string;
    "name": string;
    "canRead": boolean;
    "canWrite": boolean;
    "operations": Operation[] | null;
}

export enum Operation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReplaceFile = "replace",
    MergeList = "merge-list",
    MergeStrings = "merge-strings",
    DeleteFile = "delete",
};
