// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveService: 打开/关闭归档、状态查询、资源树懒加载与搜索。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdvancedIndexStatus returns the lazy string reverse-index status.
 */
export function AdvancedIndexStatus(): $CancellablePromise<$models.AdvancedSearchIndexStatus> {
    return $Call.ByID(2276700277);
}

/**
 * AdvancedSearch searches raw token bytes or string-pool references.
 * cursor is the result offset from the previous response; limit is 1..1000.
 */
export function AdvancedSearch(mode: string, query: string, scopePath: string, regex: boolean, cursor: number, limit: number): $CancellablePromise<$models.AdvancedSearchResult | null> {
    return $Call.ByID(3108371697, mode, query, scopePath, regex, cursor, limit);
}

/**
 * Close 关闭当前归档,丢弃未保存的内存修改。
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3538974537);
}

/**
 * IndexStatus 返回当前归档的语义搜索索引状态。
 */
export function IndexStatus(): $CancellablePromise<$models.IndexStatus> {
    return $Call.ByID(1258396651);
}

/**
 * Info 返回当前归档状态;未打开时 Path 为空。
 */
export function Info(): $CancellablePromise<$models.ArchiveInfo> {
    return $Call.ByID(1156716487);
}

/**
 * ListChildren 懒加载某目录的直接子节点;path 为空表示根。
 */
export function ListChildren(path: string): $CancellablePromise<($models.TreeNode | null)[] | null> {
    return $Call.ByID(3689351460, path);
}

/**
 * ListDescendantFiles returns all files below a directory path. An empty path
 * returns every file in the archive. Results preserve the archive path order.
 */
export function ListDescendantFiles(scopePath: string): $CancellablePromise<($models.TreeNode | null)[] | null> {
    return $Call.ByID(1570903299, scopePath);
}

/**
 * Open 加载指定路径的归档并构建目录索引。
 */
export function Open(path: string): $CancellablePromise<$models.ArchiveInfo> {
    return $Call.ByID(1804667807, path);
}

/**
 * OpenDialog 弹出文件选择框并加载归档。
 */
export function OpenDialog(): $CancellablePromise<$models.ArchiveInfo | null> {
    return $Call.ByID(4043575243);
}

/**
 * ResolveFiles resolves archive files by their normalized paths. Missing
 * paths are omitted and duplicate input paths are returned only once.
 */
export function ResolveFiles(paths: string[] | null): $CancellablePromise<($models.TreeNode | null)[] | null> {
    return $Call.ByID(2727375736, paths);
}

/**
 * Search 在路径、语义名称和 id 中做不区分大小写的子串匹配。
 * cursor 传上次返回的 NextCursor(首次传 0),limit 为本页上限(1..1000)。
 */
export function Search(query: string, cursor: number, limit: number): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(685177899, query, cursor, limit);
}

/**
 * SuggestDirectories returns directory paths with a case-insensitive prefix
 * match. An empty prefix returns no suggestions to avoid flooding the UI.
 */
export function SuggestDirectories(prefix: string, limit: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(1741104606, prefix, limit);
}
