// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutosaveService keeps a single overwriting snapshot of the current workspace
 * so an abnormal exit (crash, killed process) leaves something to recover. The
 * snapshot never touches the live archive: it is written from an isolated clone
 * and the workspace stays "unsaved" after the write.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseCachePath asks the user for a backup file location.
 */
export function ChooseCachePath(): $CancellablePromise<string> {
    return $Call.ByID(3588233147);
}

/**
 * CreateSnapshot writes the pending edits to the backup slot. The live archive
 * is left untouched: the write goes through an isolated clone, so the workspace
 * keeps its unsaved state and the source file is never modified.
 */
export function CreateSnapshot(): $CancellablePromise<void> {
    return $Call.ByID(1696877259);
}

/**
 * Discard deletes the backup slot. It reports whether a cache file was removed.
 */
export function Discard(): $CancellablePromise<boolean> {
    return $Call.ByID(3340239319);
}

/**
 * DropForSource deletes the backup only when it belongs to sourcePath. Saving or
 * closing another archive must never destroy a backup that still protects a
 * different workspace.
 */
export function DropForSource(sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(2933238364, sourcePath);
}

/**
 * DropForWorkspace drops the backup of the currently open workspace. It is the
 * exit path's "the user gave up on these edits" cleanup.
 */
export function DropForWorkspace(): $CancellablePromise<void> {
    return $Call.ByID(1885443074);
}

/**
 * PendingRecovery reports the backup left behind by an interrupted session, or
 * nil when the slot is empty.
 */
export function PendingRecovery(): $CancellablePromise<$models.RecoveryInfo | null> {
    return $Call.ByID(1111209093);
}

/**
 * Restore reopens the recorded source file and replays the backed-up edits into
 * the in-memory overlay, so the workspace ends up dirty exactly like the
 * session that was interrupted: modified markers, version changes and the save
 * target all stay consistent. The backup itself is kept until the next save or
 * an explicit discard.
 */
export function Restore(): $CancellablePromise<$models.ArchiveInfo> {
    return $Call.ByID(2260146459);
}

/**
 * Status reports the backup slot without writing anything.
 */
export function Status(): $CancellablePromise<$models.AutosaveStatus> {
    return $Call.ByID(3903292189);
}
