// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchService previews and applies multi-file edits against the current PVF.
 * Preview plans live only in memory and are invalidated by every archive
 * content mutation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply commits exactly the selected changed rows from a preview plan. An
 * empty selection is rejected so the UI cannot accidentally report success for
 * a no-op.
 */
export function Apply(planID: string, fileIndexes: number[] | null): $CancellablePromise<$models.BatchApplyResult> {
    return $Call.ByID(693272307, planID, fileIndexes);
}

/**
 * Preview builds an in-memory plan and returns its first page. It does not
 * modify the live archive or any editor overlay.
 */
export function Preview(request: $models.BatchRequest): $CancellablePromise<$models.BatchPreviewPage | null> {
    return $Call.ByID(3861460799, request);
}

/**
 * PreviewPage returns another page from the currently retained preview plan.
 */
export function PreviewPage(planID: string, cursor: number, limit: number): $CancellablePromise<$models.BatchPreviewPage | null> {
    return $Call.ByID(1058193476, planID, cursor, limit);
}
