// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookmarkService persists user books and supplies the embedded system book.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportBookmarkBookDialog saves one portable bookmark book selected by the
 * frontend. Built-in books are intentionally exportable.
 */
export function ExportBookmarkBookDialog(book: $models.BookmarkBookFile): $CancellablePromise<string> {
    return $Call.ByID(587496382, book);
}

/**
 * ImportBookmarkBookDialog opens and parses one portable bookmark book.
 */
export function ImportBookmarkBookDialog(): $CancellablePromise<$models.BookmarkBookFile | null> {
    return $Call.ByID(1853962089);
}

/**
 * LoadBookmarks loads custom books and injects the current built-in book.
 */
export function LoadBookmarks(): $CancellablePromise<$models.BookmarkDocument> {
    return $Call.ByID(3710037022);
}

/**
 * SaveBookmarks persists custom books and, in development mode, writes the
 * built-in book back to config/bookmarks.json.
 */
export function SaveBookmarks(document: $models.BookmarkDocument): $CancellablePromise<void> {
    return $Call.ByID(552992597, document);
}
