// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheService reports and clears the caches the application keeps for itself:
 * the semantic search index, the SQLite archive index, the advanced search
 * index, the NPK icon index and the timed workspace backup. Everything below
 * the cache root is either rebuilt on demand or disposable, so clearing can
 * never remove configuration, bookmarks or file sets (those live in the user
 * config directory).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear deletes every cache entry it can, leaving indexes that are still in use
 * by the running session in place.
 */
export function Clear(): $CancellablePromise<$models.CacheClearResult> {
    return $Call.ByID(25024348);
}

/**
 * Usage sums the cache without changing anything.
 */
export function Usage(): $CancellablePromise<$models.CacheUsage> {
    return $Call.ByID(3120517810);
}
