// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DropService reads and applies the four structured drop-rate files without
 * opening them as editor tabs. Changes remain in the archive overlay until the
 * regular editor save operation writes the PVF source file.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply validates and applies a complete editor snapshot atomically. The
 * revision check prevents a stale modal from overwriting a newer archive edit.
 */
export function Apply(request: $models.DropRateApplyRequest): $CancellablePromise<$models.DropRateApplyResult> {
    return $Call.ByID(4081871964, request);
}

/**
 * Read returns the current drop-rate snapshot for the opened 90US/90CN PVF.
 */
export function Read(): $CancellablePromise<$models.DropRateDocument | null> {
    return $Call.ByID(1517419244);
}
