// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditorService: 文件内容读取、内存编辑、保存/另存为、导出与整包解包。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelUnpack 请求中止进行中的解包。
 */
export function CancelUnpack(): $CancellablePromise<void> {
    return $Call.ByID(1164216096);
}

/**
 * ExportFilesDialog 将选中的文件或目录导出到目标目录,文件内容使用渲染后的 UTF-8 文本。
 * 目录会递归展开,并保留归档内的相对路径。
 */
export function ExportFilesDialog(scopes: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2444537465, scopes);
}

/**
 * GetAnnotations recomputes annotations against the exact current editor text.
 */
export function GetAnnotations(index: number): $CancellablePromise<$models.EditorAnnotation[] | null> {
    return $Call.ByID(1902721074, index);
}

/**
 * GetFile 返回文件的反编译文本(内存编辑视图)。
 */
export function GetFile(index: number): $CancellablePromise<$models.FileMeta | null> {
    return $Call.ByID(1304838230, index);
}

/**
 * IsUnpacking 报告解包是否进行中。
 */
export function IsUnpacking(): $CancellablePromise<boolean> {
    return $Call.ByID(3758982134);
}

/**
 * Save 把全部内存修改写回源文件(原子写:临时文件 + rename)。
 */
export function Save(): $CancellablePromise<$models.ArchiveInfo> {
    return $Call.ByID(1087792513);
}

/**
 * SaveAsDialog 弹出保存对话框并另存为新 PVF。返回保存路径。
 */
export function SaveAsDialog(): $CancellablePromise<string> {
    return $Call.ByID(3571654109);
}

/**
 * SetText 把编辑后的文本写入内存 overlay(不落盘)。
 */
export function SetText(index: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(1812312363, index, text);
}

/**
 * UnpackDialog 选择目录后,在后台协程把整包解包到该目录。
 * 进度通过事件 "unpack:progress" {done,total} 推送,结束发 "unpack:done"。
 */
export function UnpackDialog(): $CancellablePromise<boolean> {
    return $Call.ByID(4045253730);
}
