// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService owns one short-lived immutable preview, shared by all export
 * entry points. Source adaptation and format serialization remain independent.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mod$0 from "../internal/mod/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExecuteDialog picks the parent directory only after the frontend confirms.
 */
export function ExecuteDialog(id: string): $CancellablePromise<string> {
    return $Call.ByID(179822670, id);
}

/**
 * ExecuteSelectionDialog applies exclusions to the frozen preview. Dependencies
 * are not resolved again, so an explicitly excluded file cannot reappear.
 */
export function ExecuteSelectionDialog(id: string, excluded: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2804013576, id, excluded);
}

export function Formats(): $CancellablePromise<mod$0.Descriptor[] | null> {
    return $Call.ByID(1740817781);
}

export function Prepare(request: $models.ExportRequest): $CancellablePromise<$models.ExportPreview | null> {
    return $Call.ByID(3328806638, request);
}

export function Release(id: string): $CancellablePromise<void> {
    return $Call.ByID(999072264, id);
}
