// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileGUIService projects current editor drafts into read-only GUI documents.
 * It never commits text or mutates archive content.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReadShop reads structure from the caller's draft, and references from the
 * current archive overlay. Archive reads can populate caches, requiring Lock.
 */
export function ReadShop(fileIndex: number, text: string): $CancellablePromise<$models.ShopDocument | null> {
    return $Call.ByID(603302160, fileIndex, text);
}
