// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileGUIService reads GUI documents and applies validated edits to the overlay.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyShopEdit stages every touched file before publishing one overlay change.
 * The caller sends dirty drafts, but only files touched by this operation are
 * consumed. Revision and path checks reject another archive or stale dialog.
 */
export function ApplyShopEdit(req: $models.ShopEditRequest): $CancellablePromise<$models.ShopEditResult | null> {
    return $Call.ByID(858128996, req);
}

/**
 * ReadItem resolves the same item union used by shop lists and search pickers.
 */
export function ReadItem(id: string, drafts: $models.ShopDraft[] | null): $CancellablePromise<$models.ShopItem | null> {
    return $Call.ByID(3301299, id, drafts);
}

/**
 * ReadShop reads structure from the caller's draft, and references from the
 * current archive overlay. Archive reads can populate caches, requiring Lock.
 */
export function ReadShop(fileIndex: number, text: string): $CancellablePromise<$models.ShopDocument | null> {
    return $Call.ByID(603302160, fileIndex, text);
}
