// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadFileSets 从用户配置目录读取已保存的文件集。文件不存在时返回空文档。
 */
export function LoadFileSets(): $CancellablePromise<$models.FileSetDocument> {
    return $Call.ByID(3735616708);
}

/**
 * SaveFileSets 将全部文件集以原子方式保存到用户配置目录。
 */
export function SaveFileSets(document: $models.FileSetDocument): $CancellablePromise<void> {
    return $Call.ByID(1092143253, document);
}
