// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageService owns the NPK/IMG metadata snapshot and on-demand PNG cache.
 * It does not expose source NPK paths to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetImage decodes one indexed frame and encodes it as a PNG data URL.
 * Missing configuration, unfinished indexes, missing paths and out-of-range
 * frames intentionally return (nil, nil) so callers can render a fallback.
 */
export function GetImage(path: string, index: number): $CancellablePromise<$models.ImageData | null> {
    return $Call.ByID(3795816033, path, index);
}

/**
 * IndexStatus returns a copy of the current asynchronous scan state.
 */
export function IndexStatus(): $CancellablePromise<$models.ImageIndexStatus> {
    return $Call.ByID(23376526);
}

/**
 * Initialize loads a valid persistent snapshot, or starts an asynchronous
 * scan for the configured directory.
 */
export function Initialize(): $CancellablePromise<$models.ImageIndexStatus> {
    return $Call.ByID(935855838);
}

/**
 * RebuildIndex starts a manual rebuild. Existing image data remains available
 * through the old immutable snapshot until the new one is ready.
 */
export function RebuildIndex(): $CancellablePromise<$models.ImageIndexStatus> {
    return $Call.ByID(2411028821);
}

/**
 * SelectNPKDirectory opens the native directory chooser, persists the
 * selected path and starts a new asynchronous index generation.
 */
export function SelectNPKDirectory(): $CancellablePromise<$models.ImageIndexStatus> {
    return $Call.ByID(2689429750);
}
