// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pvf$0 from "../internal/pvf/models.js";

/**
 * ArchiveInfo 是前端可观察的归档状态快照。
 */
export type ArchiveInfo = pvf$0.ArchiveInfoView;

/**
 * FileMeta 返回给前端的单个文件视图。
 */
export interface FileMeta {
    "index": number;
    "path": string;
    "dataType": number;
    "size": number;
    "editable": boolean;
    "text": string;
    "modified": boolean;
}

/**
 * IndexStatus is the current state of the semantic search index.
 */
export interface IndexStatus {
    "state": string;
    "stage": string;
    "done": number;
    "total": number;
    "skipped": number;
    "error": string;
}

/**
 * SearchHit is one searchable file/list record.
 */
export interface SearchHit {
    "name": string;
    "id": string;
    "path": string;
    "category": string;
    "size": number;
    "dataType": number;
    "fileIndex": number;
}

/**
 * SearchResult 是一页搜索命中;NextCursor < 0 表示已扫完。
 */
export interface SearchResult {
    "hits": (SearchHit | null)[] | null;
    "nextCursor": number;
    "scanned": number;
}

/**
 * TreeNode is one entry in the explorer tree: either a directory or a file.
 */
export interface TreeNode {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "dataType": number;
    "childCount": number;

    /**
     * -1 for directories
     */
    "fileIndex": number;
    "tags"?: TreeTag[] | null;
}

/**
 * TreeTag is one list mapping displayed after a file name in the explorer.
 */
export interface TreeTag {
    "id": string;
    "name": string;
    "category": string;
}
