// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pvf$0 from "../internal/pvf/models.js";

/**
 * AdvancedSearchDetail explains why a file matched the query.
 */
export interface AdvancedSearchDetail {
    "kind": string;
    "value"?: string;
    "pool"?: string;
    "poolOffset"?: number;
    "occurrences": number;
    "tokenTypes"?: number[] | null;
    "fileFields"?: string[] | null;
    "byteOffsets"?: number[] | null;
    "tokenOffsets"?: number[] | null;
    "hex"?: string;
    "offsetsTruncated"?: boolean;
}

/**
 * AdvancedSearchHit is one file-level advanced-search result.
 */
export interface AdvancedSearchHit {
    "name"?: string;
    "path": string;
    "size": number;
    "dataType": number;
    "fileIndex": number;
    "details"?: (AdvancedSearchDetail | null)[] | null;
}

/**
 * AdvancedSearchIndexStatus describes the lazy string reverse-index state.
 */
export interface AdvancedSearchIndexStatus {
    "state": string;
    "stage": string;
    "done": number;
    "total": number;
    "error": string;
}

/**
 * AdvancedSearchResult is a paged file-level advanced-search response.
 */
export interface AdvancedSearchResult {
    "hits": (AdvancedSearchHit | null)[] | null;
    "nextCursor": number;
    "scanned": number;
}

/**
 * AniPreviewDocument is the structured preview model returned for .ani text.
 */
export interface AniPreviewDocument {
    "valid": boolean;
    "loop": boolean;
    "shadow": boolean;
    "frameMax": number;
    "frames": AniPreviewFrame[] | null;
    "issues": PreviewIssue[] | null;
}

/**
 * AniPreviewFrame is one decoded ANI frame.
 */
export interface AniPreviewFrame {
    "index": number;
    "delayMs": number;
    "layers": AniPreviewLayer[] | null;
}

/**
 * AniPreviewLayer is one image layer in an ANI frame.
 */
export interface AniPreviewLayer {
    "image": ImageReference;
    "x": number;
    "y": number;
}

export interface AnnotationReloadResult {
    "ruleCount": number;
    "relationCount": number;
}

export interface AppSettings {
    "annotationTagPlacement": string;
    "explorerOpenMode": string;
    "vimMode": boolean;
    "backupSourceOnSave": boolean;
    "npkDirectory": string;
    "theme": string;

    /**
     * AutosaveEnabled turns the timed workspace snapshot on. It is off by
     * default: the snapshot rewrites a whole PVF, so the user opts in.
     */
    "autosaveEnabled": boolean;

    /**
     * AutosavePath is the single-slot snapshot file. Empty means the platform
     * cache directory resolved by DefaultAutosavePath.
     */
    "autosavePath": string;
    "autosaveIntervalSeconds": number;
}

/**
 * ArchiveInfo 是前端可观察的归档状态快照。
 */
export type ArchiveInfo = pvf$0.ArchiveInfoView;

/**
 * AutosaveStatus is the UI-facing state of the backup slot.
 */
export interface AutosaveStatus {
    "enabled": boolean;
    "path": string;
    "defaultPath": string;
    "exists": boolean;
    "cachedAt": number;
    "sourcePath": string;
    "sizeBytes": number;
    "running": boolean;
    "lastError": string;
}

export interface BatchApplyResult {
    "appliedFiles": number;
    "fileIndexes": number[] | null;
    "modifiedCount": number;
    "revision": number;
}

export interface BatchDiffLine {
    "kind": string;
    "text": string;
    "oldLine": number;
    "newLine": number;
}

export interface BatchFilePreview {
    "fileIndex": number;
    "path": string;
    "status": string;
    "matchCount": number;
    "reason"?: string;
    "warnings"?: string[] | null;
    "diff"?: (BatchDiffLine | null)[] | null;
    "diffTruncated"?: boolean;
}

export interface BatchPreviewPage {
    "planId": string;
    "nextCursor": number;
    "requestedFiles": number;
    "matchedFiles": number;
    "matchedOccurrences": number;
    "changedFiles": number;
    "rows": (BatchFilePreview | null)[] | null;
}

export interface BatchRequest {
    "mode": string;
    "paths": string[] | null;
    "text"?: TextReplaceSpec | null;
    "operations"?: StructuredOperation[] | null;
}

/**
 * BookmarkBook is a runtime bookmark book. Builtin books are read-only in
 * packaged applications and editable when running from the repository.
 */
export interface BookmarkBook {
    "id": string;
    "name": string;
    "builtin": boolean;
    "editable": boolean;
    "groups"?: BookmarkGroup[] | null;
    "entries"?: BookmarkEntry[] | null;
}

/**
 * BookmarkBookFile is the portable JSON representation of one bookmark book.
 * IDs and runtime flags are intentionally omitted so imports always receive
 * fresh local identities and are treated as editable books.
 */
export interface BookmarkBookFile {
    "version": number;
    "name": string;
    "groups"?: BookmarkGroup[] | null;
    "entries"?: BookmarkEntry[] | null;
}

/**
 * BookmarkDocument is the complete runtime bookmark state.
 */
export interface BookmarkDocument {
    "version": number;
    "activeBookId": string;
    "books": BookmarkBook[] | null;
}

/**
 * BookmarkEntry is one PVF-internal file bookmark.
 */
export interface BookmarkEntry {
    "path": string;
    "name": string;
}

/**
 * BookmarkGroup is a recursively nested bookmark group.
 */
export interface BookmarkGroup {
    "id": string;
    "name": string;
    "groups"?: BookmarkGroup[] | null;
    "entries"?: BookmarkEntry[] | null;
}

/**
 * CacheClearResult reports what one clear pass removed.
 */
export interface CacheClearResult {
    "freedBytes": number;
    "usage": CacheUsage;
}

/**
 * CacheUsage is the disk footprint reported to the settings page.
 */
export interface CacheUsage {
    "path": string;
    "files": number;
    "totalBytes": number;

    /**
     * InUseBytes covers the indexes the running session holds open. They are
     * rebuilt once the archive is closed, so a clear pass has to skip them.
     */
    "inUseBytes": number;
}

/**
 * DropRateApplyRequest applies the complete editor snapshot atomically.
 */
export interface DropRateApplyRequest {
    "revision": number;
    "sections": (DropRateSection | null)[] | null;
}

/**
 * DropRateApplyResult reports the in-memory archive state after applying.
 */
export interface DropRateApplyResult {
    "revision": number;
    "fileIndexes": number[] | null;
    "modifiedCount": number;
}

/**
 * DropRateDocument is the structured view consumed by the drop-rate editor.
 * Rates are percentage hundredths: 1234 means 12.34%.
 */
export interface DropRateDocument {
    "pvfVersion": string;
    "revision": number;
    "sections": (DropRateSection | null)[] | null;
}

/**
 * DropRateGroup contains five rarity probabilities in percentage hundredths.
 */
export interface DropRateGroup {
    "rates": number[] | null;
}

/**
 * DropRateSection identifies one of the four supported drop files.
 */
export interface DropRateSection {
    "key": string;
    "groups": (DropRateGroup | null)[] | null;
}

export interface EditorAnnotation {
    "start": number;
    "end": number;
    "title": string;
    "content": string;
    "type": string;
    "targetFileIndex": number;
    "ruleIds"?: string[] | null;
    "image"?: ImageReference | null;
    "inlineImage"?: boolean;
    "placeholder"?: PlaceholderRef | null;
}

/**
 * EquipmentPreviewAttribute is one visible line in an equipment tooltip.
 */
export interface EquipmentPreviewAttribute {
    "label": string;
    "value": string;
    "negative": boolean;
}

/**
 * EquipmentPreviewDocument is the game-style data model rendered by the
 * frontend. Optional sections are represented by empty strings/slices.
 */
export interface EquipmentPreviewDocument {
    "icon": ImageReference | null;
    "name": string;
    "name2": string;
    "rarity": number;
    "rarityLabel": string;
    "qualityText": string;
    "equipmentType": string;
    "itemGroupName": string;
    "attachType": string;
    "minimumLevelText": string;
    "usableJobs": string[] | null;
    "baseAttributes": EquipmentPreviewAttribute[] | null;
    "fourDimensions": EquipmentPreviewAttribute[] | null;
    "otherAttributes": EquipmentPreviewAttribute[] | null;
    "skillLevelups": EquipmentSkillLevelup[] | null;
    "baseExplain": string;
    "detailExplain": string;
    "flavorText": string;
    "durabilityText": string;
    "weightText": string;
    "priceText": string;
    "issues": PreviewIssue[] | null;
}

/**
 * EquipmentSkillLevelup is one profession-aware skill level bonus.
 */
export interface EquipmentSkillLevelup {
    "job": string;
    "skill": string;
    "level": number;
}

/**
 * FileMeta 返回给前端的单个文件视图。
 */
export interface FileMeta {
    "index": number;
    "path": string;
    "dataType": number;
    "size": number;
    "tags"?: TreeTag[] | null;
    "editable": boolean;
    "text": string;
    "modified": boolean;
    "annotations"?: EditorAnnotation[] | null;
    "icon"?: ImageReference | null;
    "fieldImage"?: ImageReference | null;
}

/**
 * FileRegistration describes one indexed id/path entry in an archive list.
 */
export interface FileRegistration {
    "id": string;
    "category": string;
    "fileIndex": number;
    "filePath": string;
    "listFileIndex": number;
    "listPath": string;
    "entryPath": string;
}

/**
 * FileRegistrationOptions contains the list choices for the current file.
 */
export interface FileRegistrationOptions {
    "fileIndex": number;
    "filePath": string;
    "targets": (ListRegistrationTarget | null)[] | null;
}

/**
 * FileSetDocument 是全部文件集的持久化文档,与当前打开的 PVF 无关。
 */
export interface FileSetDocument {
    "version": number;
    "fileSets": StoredFileSet[] | null;
    "activeSetId": string;
}

/**
 * ImageData is always a PNG data URL. The source NPK path is intentionally
 * never exposed to the frontend.
 */
export interface ImageData {
    "dataUrl": string;
    "width": number;
    "height": number;
}

/**
 * ImageIndexStatus is emitted while the NPK directory is being scanned.
 */
export interface ImageIndexStatus {
    "state": string;
    "stage": string;
    "directory": string;
    "done": number;
    "total": number;
    "npkFiles": number;
    "imgFiles": number;
    "imageCount": number;
    "skipped": number;
    "duplicates": number;
    "error": string;
    "generation": number;
    "buildDurationMs": number;
}

/**
 * ImageReference is the PVF path plus zero-based frame index stored in an
 * [icon] or [field image] section.
 */
export interface ImageReference {
    "path": string;
    "index": number;
}

/**
 * ImportPreview describes the validated changes without modifying the live
 * archive. Entries is capped for large directory imports; the counters remain
 * complete.
 */
export interface ImportPreview {
    "targetDir": string;
    "mode": string;
    "totalFiles": number;
    "importedCount": number;
    "overwrittenCount": number;
    "entries": (ImportPreviewEntry | null)[] | null;
    "entriesTruncated": boolean;
}

/**
 * ImportPreviewEntry is one validated source-to-archive mapping.
 */
export interface ImportPreviewEntry {
    "sourcePath": string;
    "targetPath": string;
    "dataType": number;
    "size": number;
    "overwrite": boolean;
}

/**
 * ImportResult describes one atomically applied import operation.
 */
export interface ImportResult {
    "targetDir": string;
    "mode": string;
    "importedCount": number;
    "overwrittenCount": number;
    "changedPaths"?: string[] | null;
}

/**
 * IndexHashRegistrationResult summarizes a batch hash registration.
 */
export interface IndexHashRegistrationResult {
    "listPath": string;
    "indexHashPath": string;
    "requested": number;
    "added": number;
    "existing": number;
    "invalidIds"?: string[] | null;
}

/**
 * IndexHashTarget describes a list whose companion index-hash file exists.
 */
export interface IndexHashTarget {
    "listPath": string;
    "indexHashPath": string;
}

/**
 * IndexStatus is the current state of the semantic search index.
 */
export interface IndexStatus {
    "state": string;
    "stage": string;
    "done": number;
    "total": number;
    "skipped": number;
    "error": string;

    /**
     * Refreshing means an older ready snapshot is still serving queries while
     * a newer candidate is being built in the background.
     */
    "refreshing": boolean;
    "refreshError": string;
    "cacheHit": boolean;
    "openDurationMs": number;
    "buildDurationMs": number;
}

/**
 * ListRegistrationTarget describes a list that can register one archive file.
 */
export interface ListRegistrationTarget {
    "listPath": string;
    "category": string;
    "entryPath": string;
    "suggestedId": string;
    "hasIndexHash": boolean;
}

/**
 * PlaceholderRef identifies the string-table entry a placeholder annotation
 * resolves through, so the editor can offer to rewrite — or create — that text.
 */
export interface PlaceholderRef {
    "tableIndex": number;
    "key": string;
    "fallback"?: boolean;

    /**
     * Missing reports a placeholder no table answers yet: the editor offers to
     * create the entry, which is how a new file gets its display text.
     */
    "missing"?: boolean;
}

/**
 * PreviewIssue is a recoverable problem reported by a preview parser.
 */
export interface PreviewIssue {
    "severity": string;
    "line": number;
    "section"?: string;
    "message": string;
}

/**
 * RecoveryInfo describes a backup that can be restored on startup.
 */
export interface RecoveryInfo {
    "sourcePath": string;
    "sourceName": string;
    "cachedAt": number;
    "sizeBytes": number;
    "pendingFiles": number;
    "sourceExists": boolean;
    "sourceChanged": boolean;
}

/**
 * RenderingReloadResult describes the renderer that was activated.
 */
export interface RenderingReloadResult {
    "ruleCount": number;
}

export interface ScriptApplyResult {
    "appliedFiles": number;
    "fileIndexes": number[] | null;
    "modifiedCount": number;
    "revision": number;

    /**
     * Structural reports whether the commit changed the entry table, which
     * means every previously previewed file index is now stale.
     */
    "structural": boolean;

    /**
     * AppliedFileSets counts the file set mutations written to user config.
     */
    "appliedFileSets": number;
}

export interface ScriptCompileResult {
    "valid": boolean;
    "diagnostics": (ScriptDiagnostic | null)[] | null;
}

export interface ScriptDiagnostic {
    "kind": string;
    "message": string;
    "stack"?: string;
    "line"?: number;
    "column"?: number;
}

export interface ScriptError {
    "kind": string;
    "message": string;
    "stack"?: string;
    "line"?: number;
    "column"?: number;
}

export interface ScriptFile {
    "name": string;
    "size": number;
    "modifiedAt": string;
}

export interface ScriptFilePreview {
    /**
     * ChangeKey is the stable selection key. Structural changes shift entry
     * indexes, so the frontend must select rows by this key, not FileIndex.
     */
    "changeKey": string;
    "fileIndex": number;
    "path": string;
    "status": string;
    "matchCount": number;
    "reason"?: string;
    "warnings"?: string[] | null;
    "diff"?: (BatchDiffLine | null)[] | null;
    "diffTruncated"?: boolean;
}

/**
 * ScriptFileSetPreview describes one staged file set mutation.
 */
export interface ScriptFileSetPreview {
    "changeKey": string;
    "name": string;
    "status": string;

    /**
     * Added and Removed are the path-level difference against the persisted set,
     * so the UI can show what a setAll actually changed.
     */
    "added"?: string[] | null;
    "removed"?: string[] | null;

    /**
     * Count is the resulting entry total after the change.
     */
    "count": number;
}

export interface ScriptLog {
    "level": string;
    "message": string;
}

export interface ScriptPreviewPage {
    "planId": string;
    "nextCursor": number;

    /**
     * Filter echoes the path filter this page was built with.
     */
    "filter"?: string;

    /**
     * MatchedFiles counts every row matching the filter across all pages, so
     * the UI can report an accurate total instead of only what is loaded.
     */
    "matchedFiles": number;
    "scannedFiles": number;
    "modifiedFiles": number;
    "rows": (ScriptFilePreview | null)[] | null;

    /**
     * FileSetRows lists the staged file set mutations. They are not diffed rows,
     * but the apply step must show and select them alongside archive changes.
     */
    "fileSetRows"?: (ScriptFileSetPreview | null)[] | null;

    /**
     * FileSetSelectKey is the change key the frontend selects to apply every
     * file set mutation, mirroring how archive rows use ChangeKey.
     */
    "fileSetSelectKey"?: string;
}

export interface ScriptRunRequest {
    "name"?: string;
    "source": string;
}

export interface ScriptRunResult {
    "runId": string;
    "status": string;
    "planId"?: string;
    "scannedFiles": number;
    "modifiedFiles": number;
    "fileSetChanges": number;
    "durationMs": number;
    "logs": (ScriptLog | null)[] | null;
    "error"?: ScriptError | null;
}

/**
 * ScriptSession is the script editor state handed between the main window and
 * the detached script window. Every webview has its own Pinia store, so the
 * content has to travel explicitly.
 */
export interface ScriptSession {
    "name": string;
    "source": string;
    "savedSource": string;
}

/**
 * SearchHit is one searchable file/list record.
 */
export interface SearchHit {
    "name": string;
    "id": string;
    "path": string;
    "category": string;
    "size": number;
    "dataType": number;
    "fileIndex": number;
    "rarity": number;
    "changeKind"?: string;
    "annotations"?: TreeAnnotation[] | null;
    "pathAnnotations"?: { [_ in string]?: TreeAnnotation[] | null } | null;
    "icon"?: ImageReference | null;
    "fieldImage"?: ImageReference | null;
}

/**
 * SearchResult 是一页搜索命中;NextCursor < 0 表示已扫完。
 */
export interface SearchResult {
    "hits": (SearchHit | null)[] | null;
    "nextCursor": number;
    "scanned": number;
}

export interface ShopCategory {
    "id": string;
    "name": string;
}

export interface ShopCost {
    "kind": string;
    "itemId": string;
    "quantity": string;
    "name": string;
    "icon": ImageReference | null;
}

export interface ShopDocument {
    "revision": number;
    "name": string;
    "categoryType": string;
    "categories": ShopCategory[] | null;
    "tabs": ShopTab[] | null;
    "issues": PreviewIssue[] | null;
}

export interface ShopDraft {
    "fileIndex": number;
    "path": string;
    "text": string;
}

export interface ShopEditRequest {
    "fileIndex": number;
    "path": string;
    "text": string;
    "revision": number;
    "action": string;
    "tabIndex": number;
    "sourceStart": number;
    "categoryId": string;
    "itemId": string;
    "name": string;
    "setGold": boolean;

    /**
     * empty removes [price], "0" is an explicit zero
     */
    "gold": string;
    "setMaterials": boolean;
    "materials": ShopMaterialInput[] | null;
    "drafts": ShopDraft[] | null;
}

export interface ShopEditResult {
    "revision": number;
    "files": ShopEditedFile[] | null;
    "affectedItems": number;
    "modifiedCount": number;
}

export interface ShopEditedFile {
    "fileIndex": number;
    "path": string;
    "beforeText": string;
    "text": string;
}

export interface ShopEntry {
    "item": ShopItem;
    "sourceStart": number;
    "sourceEnd": number;
}

export interface ShopGroup {
    "categoryId": string;
    "sourceStart": number;
    "items": ShopEntry[] | null;
}

export interface ShopItem {
    "fileIndex": number;
    "path": string;
    "id": string;
    "name": string;
    "rarity": number;
    "icon": ImageReference | null;
    "costs": ShopCost[] | null;
}

export interface ShopMaterialInput {
    "itemId": string;
    "quantity": string;
}

export interface ShopTab {
    "name": string;
    "sourceStart": number;
    "groups": ShopGroup[] | null;
}

export interface StoredFileSet {
    "id": string;
    "name": string;
    "entries": StoredFileSetEntry[] | null;
}

/**
 * StoredFileSetEntry 是文件集落盘格式。fileIndex 不持久化,因为它只对当前 PVF 有效。
 */
export interface StoredFileSetEntry {
    "path": string;
    "name": string;
    "ids"?: string[] | null;
    "size": number;
    "dataType": number;
}

export interface StructuredOperation {
    "kind": string;
    "section": string;
    "tokenIndex": number;
    "value": string;
    "createIfMissing": boolean;
    "operator": string;
    "operand": string;
    "operandEnd": string;
    "anchorSection": string;
    "hasEndTag": boolean;
}

export interface TextReplaceSpec {
    "find": string;
    "replacement": string;
    "regex": boolean;
}

/**
 * TreeAnnotation is one annotation attached to a path in the explorer.
 */
export interface TreeAnnotation {
    "title": string;
    "content": string;
    "type": string;
    "ruleIds"?: string[] | null;
}

/**
 * TreeNode is one entry in the explorer tree: either a directory or a file.
 */
export interface TreeNode {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "dataType": number;
    "childCount": number;

    /**
     * -1 for directories
     */
    "fileIndex": number;
    "changeKind"?: string;
    "tags"?: TreeTag[] | null;
    "annotations"?: TreeAnnotation[] | null;
    "icon"?: ImageReference | null;
    "fieldImage"?: ImageReference | null;
}

/**
 * TreeTag is one list mapping displayed after a file name in the explorer.
 */
export interface TreeTag {
    "id": string;
    "name": string;
    "category": string;

    /**
     * Rarity is the target file's [rarity] value, or pvf.RarityUnknown when the
     * file declares none. The explorer colors the tag with it.
     */
    "rarity": number;
}

/**
 * VersionChange is a path-level worktree or commit change.
 */
export interface VersionChange {
    "path": string;
    "operation": string;
    "beforeHash"?: string;
    "afterHash"?: string;
    "beforeType"?: number;
    "afterType"?: number;
}

export interface VersionChangePage {
    "changes": (VersionChange | null)[] | null;
    "nextCursor": number;
    "total": number;
}

export interface VersionCommit {
    "id": string;
    "parentId": string;
    "message": string;
    "createdAt": number;
    "changeCount": number;
}

/**
 * VersionFileDiff contains one commit change and its logical text values
 * when the underlying PVF type is editable.
 */
export interface VersionFileDiff {
    "path": string;
    "operation": string;
    "beforeHash"?: string;
    "afterHash"?: string;
    "beforeType"?: number;
    "afterType"?: number;
    "beforeText"?: string;
    "afterText"?: string;
    "textAvailable": boolean;
}

export interface VersionHistoryPage {
    "commits": (VersionCommit | null)[] | null;
    "nextCursor": number;
}

/**
 * VersionStatus is the UI-facing version session state.
 */
export interface VersionStatus {
    "enabled": boolean;
    "loading": boolean;
    "repositoryPath": string;
    "branch": string;
    "headId": string;
    "headMessage": string;
    "changedFiles": number;
    "pendingChangeSets": number;
    "needsSave": boolean;
    "viewCommitId": string;
    "error": string;
}
