// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pvf$0 from "../internal/pvf/models.js";

/**
 * AdvancedSearchDetail explains why a file matched the query.
 */
export interface AdvancedSearchDetail {
    "kind": string;
    "value"?: string;
    "pool"?: string;
    "poolOffset"?: number;
    "occurrences": number;
    "tokenTypes"?: number[] | null;
    "fileFields"?: string[] | null;
    "byteOffsets"?: number[] | null;
    "tokenOffsets"?: number[] | null;
    "hex"?: string;
    "offsetsTruncated"?: boolean;
}

/**
 * AdvancedSearchHit is one file-level advanced-search result.
 */
export interface AdvancedSearchHit {
    "name"?: string;
    "path": string;
    "size": number;
    "dataType": number;
    "fileIndex": number;
    "details"?: (AdvancedSearchDetail | null)[] | null;
}

/**
 * AdvancedSearchIndexStatus describes the lazy string reverse-index state.
 */
export interface AdvancedSearchIndexStatus {
    "state": string;
    "stage": string;
    "done": number;
    "total": number;
    "error": string;
}

/**
 * AdvancedSearchResult is a paged file-level advanced-search response.
 */
export interface AdvancedSearchResult {
    "hits": (AdvancedSearchHit | null)[] | null;
    "nextCursor": number;
    "scanned": number;
}

export interface AnnotationReloadResult {
    "ruleCount": number;
    "relationCount": number;
}

export interface AppSettings {
    "annotationTagPlacement": string;
    "explorerOpenMode": string;
    "vimMode": boolean;
    "backupSourceOnSave": boolean;
}

/**
 * ArchiveInfo 是前端可观察的归档状态快照。
 */
export type ArchiveInfo = pvf$0.ArchiveInfoView;

export interface BatchApplyResult {
    "appliedFiles": number;
    "fileIndexes": number[] | null;
    "modifiedCount": number;
    "revision": number;
}

export interface BatchDiffLine {
    "kind": string;
    "text": string;
    "oldLine": number;
    "newLine": number;
}

export interface BatchFilePreview {
    "fileIndex": number;
    "path": string;
    "status": string;
    "matchCount": number;
    "reason"?: string;
    "warnings"?: string[] | null;
    "diff"?: (BatchDiffLine | null)[] | null;
    "diffTruncated"?: boolean;
}

export interface BatchPreviewPage {
    "planId": string;
    "nextCursor": number;
    "requestedFiles": number;
    "matchedFiles": number;
    "matchedOccurrences": number;
    "changedFiles": number;
    "rows": (BatchFilePreview | null)[] | null;
}

export interface BatchRequest {
    "mode": string;
    "paths": string[] | null;
    "text"?: TextReplaceSpec | null;
    "operations"?: StructuredOperation[] | null;
}

export interface EditorAnnotation {
    "start": number;
    "end": number;
    "title": string;
    "content": string;
    "type": string;
    "targetFileIndex": number;
    "ruleIds"?: string[] | null;
}

/**
 * FileMeta 返回给前端的单个文件视图。
 */
export interface FileMeta {
    "index": number;
    "path": string;
    "dataType": number;
    "size": number;
    "tags"?: TreeTag[] | null;
    "editable": boolean;
    "text": string;
    "modified": boolean;
    "annotations"?: EditorAnnotation[] | null;
}

/**
 * FileRegistration describes one indexed id/path entry in an archive list.
 */
export interface FileRegistration {
    "id": string;
    "category": string;
    "fileIndex": number;
    "filePath": string;
    "listFileIndex": number;
    "listPath": string;
    "entryPath": string;
}

/**
 * FileSetDocument 是全部文件集的持久化文档,与当前打开的 PVF 无关。
 */
export interface FileSetDocument {
    "version": number;
    "fileSets": StoredFileSet[] | null;
    "activeSetId": string;
}

/**
 * IndexStatus is the current state of the semantic search index.
 */
export interface IndexStatus {
    "state": string;
    "stage": string;
    "done": number;
    "total": number;
    "skipped": number;
    "error": string;
}

/**
 * SearchHit is one searchable file/list record.
 */
export interface SearchHit {
    "name": string;
    "id": string;
    "path": string;
    "category": string;
    "size": number;
    "dataType": number;
    "fileIndex": number;
    "annotations"?: TreeAnnotation[] | null;
    "pathAnnotations"?: { [_ in string]?: TreeAnnotation[] | null } | null;
}

/**
 * SearchResult 是一页搜索命中;NextCursor < 0 表示已扫完。
 */
export interface SearchResult {
    "hits": (SearchHit | null)[] | null;
    "nextCursor": number;
    "scanned": number;
}

export interface StoredFileSet {
    "id": string;
    "name": string;
    "entries": StoredFileSetEntry[] | null;
}

/**
 * StoredFileSetEntry 是文件集落盘格式。fileIndex 不持久化,因为它只对当前 PVF 有效。
 */
export interface StoredFileSetEntry {
    "path": string;
    "name": string;
    "ids"?: string[] | null;
    "size": number;
    "dataType": number;
}

export interface StructuredOperation {
    "kind": string;
    "section": string;
    "tokenIndex": number;
    "value": string;
    "createIfMissing": boolean;
    "operator": string;
    "operand": string;
    "operandEnd": string;
    "anchorSection": string;
    "hasEndTag": boolean;
}

export interface TextReplaceSpec {
    "find": string;
    "replacement": string;
    "regex": boolean;
}

export interface TreeAnnotation {
    "title": string;
    "content": string;
    "type": string;
    "ruleIds"?: string[] | null;
}

/**
 * TreeNode is one entry in the explorer tree: either a directory or a file.
 */
export interface TreeNode {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "dataType": number;
    "childCount": number;

    /**
     * -1 for directories
     */
    "fileIndex": number;
    "tags"?: TreeTag[] | null;
    "annotations"?: TreeAnnotation[] | null;
}

/**
 * TreeTag is one list mapping displayed after a file name in the explorer.
 */
export interface TreeTag {
    "id": string;
    "name": string;
    "category": string;
}

/**
 * VersionChange is a path-level worktree or commit change.
 */
export interface VersionChange {
    "path": string;
    "operation": string;
    "beforeHash"?: string;
    "afterHash"?: string;
    "beforeType"?: number;
    "afterType"?: number;
}

export interface VersionChangePage {
    "changes": (VersionChange | null)[] | null;
    "nextCursor": number;
    "total": number;
}

export interface VersionCommit {
    "id": string;
    "parentId": string;
    "message": string;
    "createdAt": number;
    "changeCount": number;
}

/**
 * VersionFileDiff contains one commit change and its logical text values
 * when the underlying PVF type is editable.
 */
export interface VersionFileDiff {
    "path": string;
    "operation": string;
    "beforeHash"?: string;
    "afterHash"?: string;
    "beforeType"?: number;
    "afterType"?: number;
    "beforeText"?: string;
    "afterText"?: string;
    "textAvailable": boolean;
}

export interface VersionHistoryPage {
    "commits": (VersionCommit | null)[] | null;
    "nextCursor": number;
}

/**
 * VersionStatus is the UI-facing version session state.
 */
export interface VersionStatus {
    "enabled": boolean;
    "loading": boolean;
    "repositoryPath": string;
    "branch": string;
    "headId": string;
    "headMessage": string;
    "changedFiles": number;
    "pendingChangeSets": number;
    "needsSave": boolean;
    "viewCommitId": string;
    "error": string;
}
