// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PreviewService parses structured preview formats from the editor's current
 * text. It intentionally does not read the archive so unsaved edits can be
 * previewed without changing the archive overlay first.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ParseANI parses the current editor text. Semantic and structural problems
 * are returned in Issues so the caller can retain the last valid preview;
 * the RPC error is reserved for service-level failures.
 */
export function ParseANI(text: string): $CancellablePromise<$models.AniPreviewDocument | null> {
    return $Call.ByID(3389020806, text);
}

/**
 * ParseEQU parses the current editor text. Archive state is only used for the
 * file path and relation lookups; text itself always comes from the caller so
 * unsaved changes are reflected immediately.
 */
export function ParseEQU(fileIndex: number, text: string): $CancellablePromise<$models.EquipmentPreviewDocument | null> {
    return $Call.ByID(4063651793, fileIndex, text);
}
