// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RenderingService manages the user-facing script rendering configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReloadRules validates the on-disk rendering rules before replacing the
 * active renderer. Invalid files leave the current renderer untouched.
 */
export function ReloadRules(): $CancellablePromise<$models.RenderingReloadResult> {
    return $Call.ByID(264833935);
}
