// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptWindowService owns the detached script workspace window and stages the
 * script session that moves between windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowScriptWindowClose lets the window close without asking the frontend. The
 * application quit path calls this so shutdown cannot stall on the script
 * window's close confirmation.
 */
export function AllowScriptWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(3414665564);
}

/**
 * CloseScriptWindow stages the final session and closes the window. The close
 * hook is what actually lets the close through, so the frontend runs its own
 * confirmation before calling this.
 */
export function CloseScriptWindow(session: $models.ScriptSession): $CancellablePromise<void> {
    return $Call.ByID(917308369, session);
}

/**
 * CloseScriptWindowIfOpen closes the detached window without a frontend
 * confirmation. It is for paths where the main surface is already going away and
 * there is no window left to run a dialog.
 */
export function CloseScriptWindowIfOpen(): $CancellablePromise<void> {
    return $Call.ByID(3009253426);
}

/**
 * FocusScriptWindow brings the detached window forward, reporting whether it was
 * there so the caller can fall back to the embedded workspace.
 */
export function FocusScriptWindow(): $CancellablePromise<boolean> {
    return $Call.ByID(4201263721);
}

/**
 * IsScriptWindowOpen reports whether the detached window currently exists.
 */
export function IsScriptWindowOpen(): $CancellablePromise<boolean> {
    return $Call.ByID(1066923173);
}

/**
 * LoadScriptSession returns the staged session, or nil when none was staged.
 */
export function LoadScriptSession(): $CancellablePromise<$models.ScriptSession | null> {
    return $Call.ByID(1405434511);
}

/**
 * OpenScriptWindow opens the detached script window, or focuses the existing one.
 * The session is staged first so a freshly created window can pick it up when it
 * starts loading its script.
 */
export function OpenScriptWindow(session: $models.ScriptSession): $CancellablePromise<void> {
    return $Call.ByID(402863877, session);
}
