// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptService executes user scripts against an isolated archive stage and
 * exposes the retained preview plan to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply commits exactly the selected changed rows from one script plan.
 */
export function Apply(planID: string, fileIndexes: number[] | null): $CancellablePromise<$models.ScriptApplyResult> {
    return $Call.ByID(1069361246, planID, fileIndexes);
}

/**
 * Cancel requests cancellation of the active script. It is idempotent.
 */
export function Cancel(): $CancellablePromise<boolean> {
    return $Call.ByID(1006017148);
}

/**
 * Compile validates script syntax without reading the current archive.
 */
export function Compile(source: string): $CancellablePromise<$models.ScriptCompileResult> {
    return $Call.ByID(190666999, source);
}

export function Discard(planID: string): $CancellablePromise<void> {
    return $Call.ByID(2392854112, planID);
}

/**
 * IsRunning reports whether a script call is currently executing.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(473827193);
}

export function ListScripts(): $CancellablePromise<($models.ScriptFile | null)[] | null> {
    return $Call.ByID(215077054);
}

export function LoadScript(name: string): $CancellablePromise<string> {
    return $Call.ByID(306185925, name);
}

export function OpenScriptDirectory(): $CancellablePromise<void> {
    return $Call.ByID(2089810056);
}

export function PreviewPage(planID: string, cursor: number, limit: number): $CancellablePromise<$models.ScriptPreviewPage | null> {
    return $Call.ByID(3664869185, planID, cursor, limit);
}

/**
 * Run executes the script against a transaction and retains a diff plan. It
 * never changes the live archive. The Wails context parameter is hidden from
 * generated TypeScript bindings and is cancelled by the explicit Cancel call
 * or by the caller closing the cancellable promise.
 */
export function Run(request: $models.ScriptRunRequest): $CancellablePromise<$models.ScriptRunResult> {
    return $Call.ByID(3354473343, request);
}

export function SaveScript(name: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(4194335044, name, source);
}

export function ScriptDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1815875880);
}
