// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3687703585);
}

export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(4275989344, settings);
}

/**
 * UpdateNPKDirectory changes only the image resource directory while
 * preserving settings added by newer versions of the application.
 */
export function UpdateNPKDirectory(directory: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2463267103, directory);
}
