// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the native updater to platforms without a visible
 * application menu, such as the Windows desktop shell.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CheckForUpdates checks the configured release source and opens the Wails
 * updater flow when an update is available.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(3771798315);
}
